version: '3'
services:
    python:
        build: .
        ports:
            - "${PYTHON_PORT}:5000"
        env_file:
            - './.env'
        volumes:
            - .:/app

    postgres:
        image: postgres
        hostname: postgres
        restart: on-failure
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ${POSTGRES_DB}
        expose:
            - '5432'
        ports:
            - '${POSTGRES_PORT}:5432'

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        restart: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - '${PGADMIN_PORT}:80'
